### ISSUE TITLE
Implement active site alignment algorithm

### ISSUE THREAD

**Issue by blackpan2** [moltimate/moltimate-backend#14]
Size Estimation: M

Allow for a search to be limited by:
* EC Number
* Pfam family
* Motif set (Question for the sponsor, will we have sets like in ProMol?)

Acceptance Criteria:
* Results are properly filtered by appropriate parameters.
* Results are still returned as apart of a batch endpoint

**Comment by jmiller656** [comment]
![image](https://user-images.githubusercontent.com/8846806/47105920-4e059380-d213-11e8-9005-3a99f8068a4b.png)
Here's the test result I'm going to be comparing to when building the search. This is for the A and P sets, for EC3 only. We're looking for 8gch

**Comment by jmiller656** [comment]
Here's my current development roadmap:

- Quickly build something that does full backbone alignment
- Return view information to frontend in order to show to the user
- Build a maximum of 5 motifs from catalytic site atlas
- Make protein comparison to motif search
- Replace the full backbone alignment with this

**Comment by steplica** [comment]
Renamed this to the actual unit of work it's become to preserve it's relevant comment history: implementing the active site alignment algorithm. Will create a new issue for this issue's original purpose.

**Comment by jmiller656** [comment]
Finished!!
